#!/usr/bin/env bash
#
# PostToolUse validation hook for the Lingonect flashcard three-example rule.
#
# Claude Code pipes a JSON payload describing the tool call on stdin, e.g.
#   { "tool_name": "Edit", "tool_input": { "file_path": "/abs/path/flashcards.html", ... }, ... }
#
# We only care about edits that touch flashcards.html. For those, we verify
# that the file still wires up the third example sentence per the rule in
# CLAUDE.md:
#
#   - #example3Section / cardExample3 DOM nodes exist
#   - card objects still carry an example3 field
#   - the OpenAI worker is still invoked to generate example3
#   - example3 generation is NOT gated behind isChineseLang()
#
# Exit 2 on failure so Claude Code surfaces the message back to the model.

set -euo pipefail

# Read the hook payload. Bail out silently if stdin is empty (e.g. manual run).
payload="$(cat || true)"
if [ -z "$payload" ]; then
  exit 0
fi

# Extract the edited file path. Prefer jq when available; fall back to a
# small python one-liner so the hook works in minimal environments.
extract_path() {
  if command -v jq >/dev/null 2>&1; then
    jq -r '.tool_input.file_path // empty' <<<"$payload"
  else
    python3 - <<'PY' <<<"$payload" 2>/dev/null || true
import json, sys
try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)
print((data.get("tool_input") or {}).get("file_path") or "")
PY
  fi
}

file_path="$(extract_path)"
if [ -z "${file_path:-}" ]; then
  exit 0
fi

# Only validate flashcards.html.
case "$file_path" in
  */flashcards.html|flashcards.html) ;;
  *) exit 0 ;;
esac

if [ ! -f "$file_path" ]; then
  exit 0
fi

errors=()

grep -q 'id="example3Section"' "$file_path" \
  || errors+=("Missing #example3Section in the card back template.")

grep -q 'cardExample3' "$file_path" \
  || errors+=("Missing cardExample3 element wiring.")

grep -q 'example3' "$file_path" \
  || errors+=("No example3 field on card objects.")

grep -q 'OPENAI_WORKER' "$file_path" \
  || errors+=("OPENAI_WORKER is not referenced; the third example must come from OpenAI.")

# The third example must be generated for every stack, not only Chinese.
# Flag the legacy pattern where example3 was wrapped in isChineseLang().
if grep -nE 'if\s*\(\s*isChineseLang' "$file_path" >/dev/null; then
  # It's only a problem if example3 assignment sits inside that guard.
  if awk '
    /if[[:space:]]*\([[:space:]]*isChineseLang/ { depth=1; inside=1; next }
    inside {
      n=gsub(/\{/,"{"); depth+=n
      n=gsub(/\}/,"}"); depth-=n
      if (/example3[[:space:]]*=/) { found=1 }
      if (depth<=0) { inside=0 }
    }
    END { exit found ? 0 : 1 }
  ' "$file_path"; then
    errors+=("example3 assignment is gated behind isChineseLang(); the third example must be generated for every stack.")
  fi
fi

if [ ${#errors[@]} -gt 0 ]; then
  {
    echo "flashcards.html violates the three-example rule (see CLAUDE.md):"
    for e in "${errors[@]}"; do
      echo "  - $e"
    done
    echo
    echo "Every flashcard must have three example sentences on the back,"
    echo "and the third must be generated by the OpenAI worker."
  } >&2
  exit 2
fi

exit 0
